global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "rabbitmq-detailed"
    metrics_path: "/metrics/detailed"
    params:
      family: ["queue_coarse_metrics"]
    static_configs:
      - targets: ["rabbitmq:15692"]
    # tmp fix https://github.com/rabbitmq/rabbitmq-server/pull/5945
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "rabbitmq_build_info"
        action: drop
      - source_labels: [__name__]
        regex: "rabbitmq_identity_info"
        action: drop
