apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  rabbitmq:
    # https://www.rabbitmq.com/production-checklist.html
    # memory should be occupy no more than the 60%
    # disk free space should be 1 time and half the memory, so at last 6 GB
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.6
      disk_free_limit.relative = 1.5
    additionalPlugins:
      - rabbitmq_federation_management
      - rabbitmq_shovel_management
      - rabbitmq_stream_management
